
---

## ðŸ§  Key Learnings

- âœ”ï¸ Hands-on experience in real-world dataset analysis  
- âœ”ï¸ Strengthened Python, pandas, seaborn, and matplotlib skills  
- âœ”ï¸ Understood practical use of data cleaning, EDA, and visual storytelling  
- âœ”ï¸ Learned sentiment interpretation from text data  
- âœ”ï¸ Gained insight into geographical and environmental factors in accidents  

---

## ðŸš€ Tools & Libraries Used

- Python  
- Pandas  
- Matplotlib  
- Seaborn  
- Plotly  
- WordCloud  
- Jupyter Notebook  

---

## ðŸ“¬ Contact Me

**Shaikh Umar Farooq**  
ðŸ“§ Email: [your-email@example.com]  
ðŸ”— LinkedIn: [https://www.linkedin.com/in/shaikh-umar-farooq-492a1831a?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BOtUECcKNT96tDRJDWvBPIw%3D%3D)  
ðŸ™ GitHub: [https://github.com/ShaikhUmarFarooq)

---

> âœ¨ Proud to be a part of the Data Science Internship at [Prodigy InfoTech](https://prodigyinfotech.dev/)  
> This repository is a reflection of my learning journey and practical skills.
